# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: hofnertech
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: dailykanji
# "service" is the name of this project. This will also be added to your AWS resource names.
service: dailykanji

provider:
  name: aws
  runtime: python3.12
  architecture: arm64

functions:
  postKanji:
    handler: handler.run
    events:
      - schedule: 
          rate: rate(15 minutes)
          enabled: true

plugins:
  - serverless-python-requirements
